name: Testes com Jest

on: pull request

jobs: 
  teste-com-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Rodando npm install e npm teste
        run: |
          npm install
          npm test